version: '3'
services:
  base-project-pg:
    container_name: ylab-postgres
    image: postgres:16
    environment:
      POSTGRES_USER: suhoi
      POSTGRES_PASSWORD: suhoi
      POSTGRES_DB: training_service_db
    ports:
      - "5432:5432"