datasource:
  url: jdbc:postgresql://localhost:5432/training_service_db
  username: suhoi
  password: suhoi
  pool-size: 10
liquibase:
  change-log: db/changelog/changelog.xml
  liquibase-schema: services